CREATE TABLE IF NOT EXISTS Ingredient (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    name VARCHAR(255),
    type VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Taco (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Taco_Ingredients (
    taco_id BIGINT NOT NULL,
    ingredients_id VARCHAR(255) NOT NULL,
    CONSTRAINT fk_taco_ingredient_taco FOREIGN KEY (taco_id) REFERENCES Taco(id),
    CONSTRAINT fk_taco_ingredient_ingredient FOREIGN KEY (ingredients_id) REFERENCES Ingredient(id)
);

CREATE TABLE IF NOT EXISTS Taco_Order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placed_at TIMESTAMP,
    user_id BIGINT,
    cc_expiration VARCHAR(255),
    cc_number VARCHAR(255),
    cccvv VARCHAR(255),
    city VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    state VARCHAR(255) NOT NULL,
    street VARCHAR(255) NOT NULL,
    zip VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Taco_Order_Tacos (
    order_id BIGINT NOT NULL,
    tacos_id BIGINT NOT NULL,
    CONSTRAINT fk_order FOREIGN KEY (order_id) REFERENCES Taco_Order(id),
    CONSTRAINT fk_taco FOREIGN KEY (tacos_id) REFERENCES Taco(id)
);

CREATE TABLE IF NOT EXISTS Users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255),
    password VARCHAR(255),
    fullname VARCHAR(255),
    phone_number VARCHAR(255),
    street VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255),
    zip VARCHAR(255)
);

ALTER TABLE Taco_Order
    ADD CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES Users(id);
